### PR TITLE
V7.3.13

### LINKED ISSUE #109: Problem with cython-generated code: `cython_function_or_method' is not an acceptable base type`
There are problems with cython generated code that turn up when importing SciPy. This affects any feedstock that is using SciPy.

I think the problem is the seires of patches I applied after the 7.3.12 release to better support multi-phase c-extension initialization. I have further fixes on the upstream PyPy code, and will make a 7.3.13 release to re-synch the feedstock with those fixes.

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.
- Update to pypy7.3.13 for python3.9, drop building python3.8 (since it is no longer getting updates)
- remove patches and build script segments for python3.8 and for updates after 7.3.12

Fixes #109 (tested by creating an environment with 7.3.12, installing pandas, reproducing the failure. Then substituting the libpypy3.9-c.so with the one from this build and checking that the failure is gone).

### CODE REVIEW

**Comment by mattip** [comment]
Windows [is failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=791809&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc&l=9467) with
```
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\bld\pypy3.9_1695978865364\_test_env\Lib\zoneinfo\_zoneinfo.py", line 43, in __new__
    instance = cls._weak_cache.setdefault(key, cls._new_instance(key))
  File "D:\bld\pypy3.9_1695978865364\_test_env\Lib\zoneinfo\_zoneinfo.py", line 70, in _new_instance
    file_obj = _common.load_tzdata(key)
  File "D:\bld\pypy3.9_1695978865364\_test_env\Lib\zoneinfo\_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key America/Los_Angeles'
```

It was similarly failing in #108. Is this something that should be skipped on windows?

**Comment by mattip** [comment]
Ahh, I removed too much from meta.yaml

**Review by h-vetinari — APPROVED** [review]
Cool, happy to see this being fixed!

**Comment by h-vetinari** [comment]
> merging this will require an additional PR

For completeness: merging here is fine (actually, a prerequisite); the pypy-meta PR is just necessary so that 7.3.13 is generally available.

**Comment by mattip** [comment]
Self merging to move this forward

**Pull request merged**
