### PR TITLE
patch for Issue 4010 (debug cruft leftover)

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See [issue 4010](https://foss.heptapod.net/pypy/pypy/-/issues/4010). Debug cruft left in the release is confusing when parsing stdout.

Also cleaned up unused patches

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
This issue appears to be causing `pyproj` tests to fail with PyPy so this fix is very much appreciated!

**Comment by mattip** [comment]
CI is passing. I will leave it for a day or two in case someone else wants to take a look. Once this is merged I will try to build the ppc64le and arm64 packages as well, and will post the logs here when it is ready.

**Comment by xylar** [comment]
@mattip, is is maybe time to merge this?  We `pyproj` maintainers would be keen!

**Comment by mattip** [comment]
Done. Wait a few hours for the package to update.

**Comment by xylar** [comment]
Great, thanks very much!

**Comment by mattip** [comment]
@isuruf could you copy the two files marked with the "copy" label from https://anaconda.org/mattip/pypy3.9/files? Here are the build logs
[ppc64le_log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/13179310/ppc64le_log.txt)
[aarch64_log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/13179311/aarch64_log.txt)

**Comment by xylar** [comment]
@isuruf and @mattip, did the ppc64le and aarch64 builds ever get uploaded?  We're still seeing build fails for PyPy for those architectures on https://github.com/conda-forge/pyproj-feedstock/pull/146.

**Comment by isuruf** [comment]
Just copied now. Sorry. Thanks @mattip for building.

**Pull request merged**
