### PR TITLE
update to pypy v7.3.16

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
To complete the release process, after merging this:
- the aarch64 and ppc64le packages need to be built manually and a conda-forge maintainer must upload them
- a PR to update the [meta-feedstock](https://github.com/conda-forge/pypy-meta-feedstock) needs to be merged

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
CI is passing

**Review by h-vetinari — APPROVED** [review]
LGTM! Thank you!

**Comment by mattip** [comment]
I built and uploaded the ppc64 and aarch64 packages to https://anaconda.org/mattip/pypy3.9/files, and marked them with the "copy" label. Here are the build logs:
[ppc64-conda-log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/15253512/ppc64-conda-log.txt)
[arm64-log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/15253513/arm64-log.txt)

Could someone with permissions upload them to https://anaconda.org/conda-forge/pypy3.9/?

I made a PR to the [meta-feedstock](https://github.com/conda-forge/pypy-meta-feedstock), that should only be merged once the packages are copied.

**Comment by h-vetinari** [comment]
Done, thank you!
```
>set "LABEL=copy"
>set "DELEGATE=mattip"
>set "PACKAGE_VERSION=7.3.16"
>anaconda copy --from-label %LABEL% --to-label main --to-owner conda-forge %DELEGATE%/pypy3.9/%PACKAGE_VERSION%
Using Anaconda API: https://api.anaconda.org
Copied file: linux-aarch64/pypy3.9-7.3.16-h2117f8e_0.tar.bz2
Copied file: linux-ppc64le/pypy3.9-7.3.16-hee5ce64_0.tar.bz2
Copied 2 files!
```

**Pull request merged**
