### PR TITLE
add patches for glibc-detection, numpy segfault on win, `get_python_lib`

### PR DESCRIPTION
**Pull request by h-vetinari**
Fixing https://foss.heptapod.net/pypy/pypy/-/issues/3502 as [suggested](https://github.com/conda-forge/numpy-feedstock/pull/237#issuecomment-872016825) by @mattip:
> PyPy issue is fixed. Is it worth making a patch and releasing a new pypy7.3.5 build? The next PyPy release will probably be a few months coming, and I don't know how common it is to use PyPy + centos7

### CODE REVIEW

**Review by mattip — APPROVED** [review]
While the patch fixes the `os.confstr` incompatibility, I don't know if the cost to users and/or conda-forge to update the build number for this is worth it. Does it dsrupt anything to accept it?

**Comment by h-vetinari** [comment]
> I don't know if the cost to users and/or conda-forge to update the build number for this is worth it. Does it dsrupt anything to accept it?

It's a normal part of the process. It means people using pypy download the new package when they update their environment (creating some more CDN traffic), but otherwise, the infrastructural costs are negligible (still takes reviewer time, of course, but you've done >90% of the work there by implementing the fix and approving it 🙃).

And of course, it helps with the blas-testing for numpy (or someone wanting to run the numpy test suite on an AVX512 machine). 😉

**Comment by mattip** [comment]
> run the numpy test suite on an AVX512 machine

... but still stuck with CentOS6 which went EOL 7 months ago

**Comment by mattip** [comment]
I am working on more fixes for PyPy + Windows + NumPy, so maybe let's wait a day or two to see if I can add another patch here

**Comment by mattip** [comment]
I pushed some more fixes:
- renamed the patch @h-vetinari added since it will be part of pypyv7.3.6
- added another patch that is also part of v7.3.6. It seems to solve the segfault on win64 when testing numpy
- added a patch to fix the schema used in `get_python_lib` from `distutils.sysconfig` to make it match CPython's ersion. I limited it to windows, but I think the schema changes in both the distutil* patches should also apply to linux. @isuruf thoughts?

**Comment by mattip** [comment]
The `get_python_libs` function is not commonly uses. NumPy uses it [in `runtests.py`](https://github.com/numpy/numpy/blob/f53996b28bb5251c0888c2550919c19daf8e79f9/runtests.py#L478)

**Comment by h-vetinari** [comment]
Thanks Matti, LGTM! :)

**Comment by h-vetinari** [comment]
@isuruf, could you take a look here please? I'd love to unblock the win-pypy numpy build, which will [likely](https://github.com/conda-forge/numpy-feedstock/pull/238#issuecomment-872365485) still take another iteration after this.

**Comment by h-vetinari** [comment]
Thanks! :)

**Pull request merged**
