### PR TITLE
Ppc64le and aarch64 (DRAFT)

### PR DESCRIPTION
**Pull request by ohadravid**
Just wanted to see what the CI says about this

--------

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ohadravid** [comment]
@isuruf I force-pushed here, but I made a backup of the old branch here https://github.com/ohadravid/pypy3.6-feedstock/tree/ppc64le-and-aarch64-old

**Comment by isuruf** [comment]
Using azure will most probably not work as well as it's running on QEMU. If a build takes more than an hour on native hardware, it'll most certainly take more than 6 hours on emulated.

**Comment by mariusvniekerk** [comment]
@isuruf we can probably try travisci here.  Pretty sure we can just do that as is atm without needing any changes to smithy

**Comment by isuruf** [comment]
Why? Drone gives 1 hour and Travis-CI gives 50 minutes.

**Comment by mariusvniekerk** [comment]
true, and we need like 2 hours in any case

**Pull request closed without merging**
