### PR TITLE
V7.3.8

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update for PyPy7.3.8:
- drop python3.7
- update python3.8
- add python3.9

### CODE REVIEW

**Comment by h-vetinari** [comment]
Great to see this! :)

There's a bunch of patches that are version-guarded and probably need to be "unlocked" for pypy 3.9, e.g.:
```
      - patches/0018-Disable-copying-dlls.patch  # [name_suffix == "3.7"]
      - patches/0019-Disable-copying-dlls.patch  # [name_suffix == "3.8"]
      - patches/0021-Adapt-platform-to-patch-0001.patch
      - patches/0022-Fix-LIBDIR.patch  # [name_suffix == "3.7"]
      - patches/0023-Fix-LIBDIR.patch  # [name_suffix == "3.8"]
```

**Comment by mattip** [comment]
Something strange is happening on windows. The `copy a*.lib b.lib` is only partially copying the file.
```
(%BUILD_PREFIX%) %SRC_DIR%\usession-pypy3-0\testing_1>copy *.lib %SRC_DIR%\pypy3\libs\python38.lib   || exit /b 11 
libpypy3-c.lib
        1 file(s) copied.

(%BUILD_PREFIX%) %SRC_DIR%\usession-pypy3-0\testing_1>REM how big is the lib? It should be about 200k 

(%BUILD_PREFIX%) %SRC_DIR%\usession-pypy3-0\testing_1>dir *.lib 
 Volume in drive D is Temporary Storage
 Volume Serial Number is 3A31-7486

 Directory of %SRC_DIR%\usession-pypy3-0\testing_1

02/21/2022  09:19 AM           210,038 libpypy3-c.lib
               1 File(s)        210,038 bytes
               0 Dir(s)  11,379,363,840 bytes free

(%BUILD_PREFIX%) %SRC_DIR%\usession-pypy3-0\testing_1>dir %SRC_DIR%\pypy3\libs\python38.lib 
 Volume in drive D is Temporary Storage
 Volume Serial Number is 3A31-7486

 Directory of %SRC_DIR%\pypy3\libs

02/21/2022  09:19 AM               648 python38.lib
               1 File(s)            648 bytes
               0 Dir(s)  11,379,363,840 bytes free
```

**Comment by mattip** [comment]
Got it: copy should use the /b switch: `copy /b src target`. I don't know why this didn't come up before. Maybe because there is a wild-card `*` in the `src` but not in the `target`

**Comment by mattip** [comment]
All CI is green. @isuruf could you take a look?

**Comment by mattip** [comment]
In order to make `tox` testing work, I think we need the fix for [the venv inside a venv](https://foss.heptapod.net/pypy/pypy/-/issues/3323#note_173950) issue. I will add a patch.

**Comment by mattip** [comment]
Patch added, CI is still green. Anyone care to take a look?

**Review by h-vetinari — APPROVED** [review]
> Patch added, CI is still green. Anyone care to take a look?

Not that I'm particularly qualified to do so, but LGTM!

**Comment by isuruf** [comment]
I've started 4 builds each on the ppc64le and aarch64 server. Will take a day for these to get built.

**Comment by mattip** [comment]
cool, thanks. So I won't do it :100:

**Comment by h-vetinari** [comment]
Not sure if spurious or whether something changed since the CI ran on this PR, but `osx_64_name_suffix3.8openssl1.1.1` failed with an AssertionError during translation after this was merged to master.

**Comment by h-vetinari** [comment]
Seems that the error should be resolvable by a restart; at least #74 doesn't seem to run into the same problem.

**Pull request merged**
