### PR TITLE
temporary fix in buffer format size

### PR DESCRIPTION
**Pull request by mattip**
It turns out hard-coding the format length was a bad idea, and causes various problems with scikit-learn. This is a temporary fix, a more permanent one will be in the next version of PyPy
xref scikit-learn/scikit-learn#18624
xref scikit-learn/scikit-learn#17994

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
xref https://foss.heptapod.net/pypy/pypy/-/issues/3336, which was fixed by [this commit](https://foss.heptapod.net/pypy/pypy/-/commit/9054a23f8fcb6f58f69634839664f40ddcdb35b6). If this PR can wait a day, I will update it after the fix is tested. If not I can make another PR.

**Comment by ogrisel** [comment]
I think it's fine to wait a day or two for scikit-learn if this leads to a lower maintenance fix. We plan to start the work on a scikit-learn 0.24 release branch for a beta or rc next week.

**Comment by ogrisel** [comment]
Thanks very much for investigating and fixing this @mattip.

**Comment by mattip** [comment]
Sorry for the mess. I wonder why the PR to build scikit-learn on conda didn't hit this? Is it new?

**Comment by mattip** [comment]
xref conda-forge/scikit-learn-feedstock#130 which passed

**Comment by ogrisel** [comment]
> Sorry for the mess. I wonder why the PR to build scikit-learn on conda didn't hit this? Is it new?

It has been failing for a while. I am not sure when it started failing (maybe after a new release of Cython?). Given the lack of familiarity of scikit-learn developers with such a low level and terse exception message, I guess nobody had the will to investigate but this was starting to block the upcoming 0.24 release, hence the renewed interest in investigating this.

**Comment by ogrisel** [comment]
@mattip would it be possible to try to enable:

```yaml
azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: True
```
in `conda-forge.yml` in this PR to make it possible to download the generated pypy conda package to test locally that this fixes the segfault in scikit-learn?

 https://conda-forge.org/docs/maintainer/conda_forge_yml.html#azure

**Comment by mattip** [comment]
@ogrisel done. You could also try the latest nightly from https://buildbot.pypy.org/nightly/py3.6/ for the permanent fix, although then you would have to install all the dependencies. If you choose to go that route, it would be even better to try out the PyPy 3.7 beta available at https://buildbot.pypy.org/nightly/py3.7.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by ogrisel** [comment]
@isuruf the build went well and it seems to have published the artifacts somewhere:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235274&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=b1825a5b-56f4-5ef8-aa3b-5ba38b21028a&l=35

but the logs do not mention the URL of the generated artifact. Do you know how to use conda to install those?

**Comment by isuruf** [comment]
You should see a link that says `2 published` at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235274&view=results

**Comment by ogrisel** [comment]
Thanks I missed that.

**Comment by ogrisel** [comment]
@mattip I confirm that this patches works to fix the segfaults that we observed when importing scikit-learn modules under PyPy.

**Comment by mattip** [comment]
Thanks @ogrisel. I am still ironing out the last things for a new PyPy release, it will be at least a week probably more to get the updated version into this feedstock. If that is too slow, we could merge this to unblock scikit-learn. @isuruf thoughts? I am not clear on how "expensive" an ABI-compatible update is.

**Comment by isuruf** [comment]
>  If that is too slow, we could merge this to unblock scikit-learn. @isuruf thoughts? I am not clear on how "expensive" an ABI-compatible update is.

It's the almost the same work for both.
1. Merge this PR and let CI build `linux-64`, `osx-64`
2. Build ppc64le and aarch64 manually
3. Rebuild `pypy-meta-feedstock` if a version change.

**Comment by ogrisel** [comment]
Let's not duplicate efforts then. We won't release scikit-learn final this week. Probably an rc next week and scikit-learn 0.24 final in two weeks.

**Comment by ogrisel** [comment]
And we can always re-release a quick bugfix release 0.24.1 if we discover other issues with PyPy in the after the release.

**Comment by isuruf** [comment]
If you don't need pcp64le or aarch64, we can just merge this. No other work needed.

**Comment by ogrisel** [comment]
> If you don't need pcp64le or aarch64, we can just merge this. No other work needed.

+1, that would already be a net improvement (I think), if it does not add any maintenance burden on your side.

**Comment by isuruf** [comment]
Packages should be up in ~2 hours

**Comment by ogrisel** [comment]
Thanks all, I confirm that this fixes the issue when installing pypy from conda-forge.

**Pull request merged**
