### PR TITLE
remove __init__.py from top level stdlib

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

In response to [this comment](https://github.com/pypy/pypy/issues/4885#issuecomment-1982149448) rebuild with a patch to remove the `__init__.py`

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks a lot for the PR. It seems the patch doesn't apply to 7.3.15 as-is. Now that pypy is on git, I'd be able to fix that myself as well, if you'd like.

**Comment by mattip** [comment]
Uhh, thanks for the ping. I didn't `git add` the patch file, sorry.

**Review by h-vetinari — APPROVED** [review]

**Comment by mattip** [comment]
@h-vetinari are you seeing CI failures because of this on ppc64le and aarch64 as well? If so I should build out this PR on those platforms manually

**Comment by h-vetinari** [comment]
Yes, the do appear on the arches as well, see https://github.com/conda-forge/labmaze-feedstock/pull/11 or https://github.com/conda-forge/numpy-feedstock/pull/310

**Comment by mattip** [comment]
I uploaded the aarch64 and ppc64le artifacts to https://anaconda.org/mattip/pypy3.9/files, and marked them with a `copy` label. Here are the logs 
[ppc64-conda-log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/14549967/ppc64-conda-log.txt)
[arm64-log.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/14549968/arm64-log.txt)

**Comment by mattip** [comment]
cc @isuruf to copy the ppc64le and aarch64 packages from  https://anaconda.org/mattip/pypy3.9/files to conda-forge

**Pull request merged**
