### PR TITLE
update to v7.3.11

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Part 1 of #98. Note that in the mean time CPython released security fixes for python3.8.16, python3.9.16, it may be worthwhile adding patches for those.

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
CI is passing @conda-forge/pypy3.6 any thoughts?

**Review by h-vetinari — APPROVED** [review]
> CI is passing. Anyone care to review?

Not that it says much, but this LGTM :)

**Comment by h-vetinari** [comment]
Ah, and I was wondering about osx-arm support - it's mentioned in the [announcement](https://www.pypy.org/posts/2022/12/pypy-v7310-release.html), but I guess it makes sense to tackle this in a separate PR. Or is cross-compilation still a ways away?

**Comment by mattip** [comment]
> it makes sense to tackle this in a separate PR

I think so. I don't know if cross-compilation is an option since it will be very slow. I already build aarch64 and ppc64le outside CI, I could do the same for arm64. However I would want buy-in from the conda-forge team, since it would mean starting a migration for binary packages.

**Comment by mattip** [comment]
>     it makes sense to tackle this in a separate PR

xref #88

**Comment by h-vetinari** [comment]
> I don't know if cross-compilation is an option since it will be very slow

Why should it be slow? For aarch/ppc the compilation essentially runs with native (=host) speed. What's slow is _emulating_  one arch through another (e.g. pretend you're aarch64 while running on actual x64 hardware).

But yeah, it would need a new migration (like for pypy-windows at the time), and likely a bunch of effort to get the bootstrap and the first couple of key packages off the ground.

**Comment by mattip** [comment]
I think I was confused. cross-compilation (using a different compiler chain and tricking python `platform`, `sys`, `os`, `sysconfig` and other modules) is not tested and probably will not work out-of-the-box with the PyPy builds. Using qemu on x86 to emulate arm64 will be slow, which is why we build the aarch64 and ppc64le outside of CI.

**Comment by mattip** [comment]
This should be patched for [issue 3865](https://foss.heptapod.net/pypy/pypy/-/issues/3865) so the macos-x86_64 will run on older macos<11. The patch is [this commit](https://foss.heptapod.net/pypy/pypy/-/commit/29a6d0d51a75ab1b1bf7fb177230d434da15441d)

**Comment by h-vetinari** [comment]
@mattip 
Could you upgrade to 7.3.11 here?

**Comment by mattip** [comment]
> Could you upgrade to 7.3.11 here?

Done

**Comment by mattip** [comment]
> This should be patched for [issue 3865](https://foss.heptapod.net/pypy/pypy/-/issues/3865)

Also done, this was the main reason for v7.3.11

**Comment by mattip** [comment]
> CPython released security fixes for python3.8.16, python3.9.16, it may be worthwhile adding patches for those.

Also done :)

**Comment by mattip** [comment]
CI is passing.

Once this is merged I will build the ppc64le and aarch64 artifacts outside of CI according to [this gist](https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22)

**Comment by h-vetinari** [comment]
I think this is ready, no?

**Comment by mattip** [comment]
It has been a week. If no other reviewer does so before, I will merge soon and then create the other artifacts.

**Comment by mattip** [comment]
When trying to follow the [procedure to build for aarnch64 and ppc64le](https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22) I am hitting an error when rerendering.
```
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '3.8.* *_cpython'
```

<details><summary>complete traceback</summary>

```
$ conda-smithy rerender
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2023.01.20.05.27.27
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpvr_7j9ho
INFO:conda_smithy.configure_feedstock:openssl3.yaml from feedstock is ignored and upstream version is used
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I tru
st that you know what you're doing.
WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a
 non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you 
know what you're doing.
WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-nat
ive arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /tmp/tmpvr_7j9ho/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /tmp/tmpvr_7j9ho/conda_build_config.yaml
Adding in variants from /home/matti/pypy3.6-feedstock/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/matti/pypy3.6-feedstock/recipe/conda_build_config.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpvr_7j9ho/share/conda-forge/migrations/openssl3.yaml
Adding in variants from argument_variants
INFO:conda_build.variants:Adding in variants from argument_variants
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpvr_7j9ho/share/conda-forge/migrations/openssl3.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpvr_7j9ho/share/conda-forge/migrations/openssl3.yaml
Traceback (most recent call last):
  File "/home/matti/miniconda3/envs/builder/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_smithy/cli.py", line 670, in main
    args.subcommand_func(args)
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_smithy/cli.py", line 486, in __call__
    self._call(args, tmpdir)
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_smithy/cli.py", line 491, in _call
    configure_feedstock.main(
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 2277, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 1389, in render_azure
    return _render_ci_provider(
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 690, in _render_ci_provider
    metas = conda_build.api.render(
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/api.py", line 38, in render
    metadata_tuples = render_recipe(recipe_path, bypass_env_check=bypass_env_check,
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/render.py", line 849, in render_recipe
    rendered_metadata = distribute_variants(m, variants,
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/render.py", line 711, in distribute_variants
    used_variables = metadata.get_used_loop_vars(force_global=False)
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/metadata.py", line 2558, in get_used_loop_vars
    for var in self.get_used_vars(
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/metadata.py", line 2661, in get_used_vars
    meta_yaml_reqs = self._get_used_vars_meta_yaml(
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/metadata.py", line 2746, in _get_used_vars_meta_yaml
    reqs_text, recipe_text = self._get_used_vars_meta_yaml_helper(
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/metadata.py", line 2714, in _get_used_vars_meta_yaml_helper
    recipe_text = self.get_recipe_text(
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/metadata.py", line 2013, in get_recipe_text
    ns_cfg(self.config),
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/metadata.py", line 102, in ns_cfg
    defaults = variants.get_default_variant(config)
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/variants.py", line 109, in get_default_variant
    base.update(_get_default_compilers(config.platform, python))
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/conda_build/variants.py", line 90, in _get_default_compilers
    if parse_version(py_ver) >= parse_version('3.5'):
  File "/home/matti/miniconda3/envs/builder/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '3.8.* *_cpython'
``

**Comment by mattip** [comment]
The error above is on aarch64. On ppc64le that error is a warning.

**Comment by mattip** [comment]
Starting over from an updated base environment seems to have allowed the build process to complete.

**Comment by mattip** [comment]
@isuruf the conda-forge-p8-1 machine at 140.211.169.173 is out of disk space. Is there a way to clean up something there or to get a larger disk?

**Comment by mattip** [comment]
@beckermr do you known anything about the ppc64le conda-forge-p8-1 machine at 140.211.169.173 ? It does not have enough disk space to allow me to build the ppc64le packages for this feedstock, as I have been able to do in the past following [this gist](https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22). The builds are too slow to use a cross-compilation workflow.

**Comment by isuruf** [comment]
Cleaned up the VM. Have a look now.

**Comment by mattip** [comment]
I uploaded ppc64le and aarch64 tarballs to https://anaconda.org/mattip/pypy3.8/files and https://anaconda.org/mattip/pypy3.9/files and marked them with the "copy" label. There should be 4 files in each location.

Here are the build logs

[ppc64le-logs.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/10551434/ppc64le-logs.txt)
[aarch64-logs.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/10551435/v7.3.11-aarch64-logs.txt)

xref @isuruf could you copy the files to https://anaconda.org/conda-forge/pypy3.8 and https://anaconda.org/conda-forge/pypy3.9 ?

**Comment by isuruf** [comment]
Done

**Comment by mattip** [comment]
Thanks!

**Pull request merged**
