### PR TITLE
build both 3.6 and 3.7

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattip** [comment]
Cool. I guess this is an example of [build variants](https://conda.io/projects/conda-build/en/latest/resources/variants.html#build-variants) ? Maybe this can be added as an example there.

**Review by mattip — APPROVED** [review]

**Comment by mattip** [comment]
Thanks. I can now install pypy via `conda create -n pypy37 pypy3.7`. It seems more work is needed to start a migration of packages to pypy3.7: when I do `conda activate pypy37; conda install numpy`, conda tries to override pypy3.7 with cpython3.9.0.

**Comment by isuruf** [comment]
First we need https://github.com/conda-forge/pypy-meta-feedstock then a PR to https://github.com/conda-forge/conda-forge-pinning-feedstock

**Comment by mattip** [comment]
Sorry, I am not sure how I would do those.

**Comment by isuruf** [comment]
First we need to build both 3.6 and 3.7 python meta-packages as in this PR in https://github.com/conda-forge/pypy-meta-feedstock/blob/master/recipe/meta.yaml. I'll send a PR later this week if you don't beat me to it

**Pull request merged**
