### PR TITLE
Typo

### LINKED ISSUE #90: Broken cross-compilation with latest build
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With the last PR (https://github.com/conda-forge/pypy3.6-feedstock/pull/87) cross-compilation seems to be broken on linux-aarch64 (not linux-ppc64le though). The `cross-python` activation simply fails with the following output:

```
Setting up cross-python
ERROR: 'HOST_GNU_TYPE'
```

Running the activation using `bash -x`, I can see it breaks at the following line:

```
++++ /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_build_env/bin/python -m crossenv /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_h_env_placehold_placehold_placehold_placehold_placehold_plac
ehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python --sysroot /home/uwe/mambaforge/conda-bld/awscrt_16
65480308769/_build_env/aarch64-conda-linux-gnu/sysroot --without-pip /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_build_env/venv --sysconfigdata-file /home/uwe/mambaforge/conda-bld/awscrt_16654803
08769/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
laceh/lib/pypy3.8/_sysconfigdata__linux_aarch64-linux-gnu.py --cc /home/uwe/mambaforge/conda-bld/awscrt_1665480308769/_build_env/bin/aarch64-conda-linux-gnu-cc --cxx c++
```

### Installed packages

```shell
pypy3.9:            7.3.9-h57c6639_4     conda-forge
```

### Environment info

```shell
-
```

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #90 

Fix a typo that prevented setting `HOST_GNU_TYPE`

### CODE REVIEW

**Comment by mattip** [comment]
Maybe worthwhile to download the artifact and make sure the value is set.

**Comment by isuruf** [comment]
Or add `ls $(pypy -c "from distutils import sysconfig; print(sysconfig.get_config_var('HOST_GNU_TYPE'))")`

**Review by isuruf — APPROVED** [review]
Would you be able to build the ppc64le and aarch64 packages manually?

**Comment by mattip** [comment]
I don' think this is correct yet. I do see this in the log
```
pypy -m sysconfig --generate-posix-vars HOST_GNU_TYPE x86_64-pc-linux-gnu
```

but then the check added in the last commit fails
```
HOST_GNU_TYPE None
```

**Comment by mattip** [comment]
Maybe that is a problem with the way sysconfig is running the test, and it is fixed when the uploadable artifact is created. I will try the recipe on the aarch64 machine where I can examine the actual artifact.

**Comment by mattip** [comment]
another bug, I hope the fix does not break the early stages of the setup

**Comment by isuruf** [comment]
Need to fix `distutils/sysconfig_pypy.py` too

**Comment by mattip** [comment]
While the value does not appear in the log, after bundling the tar.gz and opening it, I do see a value for HOST_GNU_TYPE.

**Comment by isuruf** [comment]
Sure. That's because `distutils/sysconfig_pypy.py` uses `_sysconfigdata.py` instead of the generated `_sysconfigdata__linux_x86_64-linux-gnu.py`.

**Comment by mattip** [comment]
Got it: [crossenv](https://github.com/benfogle/crossenv/blob/5c3b53aa2989fc442194e144fac90464dd4b3086/crossenv/__init__.py#L188) same mechanism as the check you added to find the `_sysconfigdata*.py` file. So it is OK that `sysconfig.get_config_var('HOST_GNU_TYPE') comes back empty, as long as it is in the `_sysconfigdata*.py` file

Sorry for the noise. I think this is ready.

**Comment by isuruf** [comment]
Can you build the ppc64le and aarch64 packages?

**Comment by mattip** [comment]
yes. hopefully by the weekend

**Comment by mattip** [comment]
I uploaded 4 files each to https://anaconda.org/mattip/pypy3.8/files and https://anaconda.org/mattip/pypy3.9/files and added the "copy" label. Here are the build logs
[ppc64le_logs.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/9817019/ppc64le_logs.txt)
[aarch64_logs.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/9817020/aarch64_logs.txt)
@isuruf could you copy the files to https://anaconda.org/conda-forge/pypy3.8/files and https://anaconda.org/conda-forge/pypy3.9/files

**Comment by chrisburr** [comment]
I've just taken care of copying them, thanks @mattip!

**Pull request merged**
