### PR TITLE
add patch fixing GenericAlias on 3.9

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes incompatibility with types.GenericAlias, discovered in the numpy-feedstock conda-forge/numpy-feedstock#263 and fixed in https://foss.heptapod.net/pypy/pypy/-/issues/3720

Also refactored an import of `inspect` in `_ctypes` to avoid importing too many other modules. This came up in a name clash where [gobject-introspection](https://github.com/conda-forge/gobject-introspection-feedstock/pull/55#issuecomment-1085430249) has its own `ast` module that clashes with the stdlib one.

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
CI is passing. Could someone review?

**Review by h-vetinari — APPROVED** [review]

**Comment by lithomas1** [comment]
Unrelated, but can you also delete the ``pre-7.3.9`` patches? I forgot to do that in my other PR. Thanks.

**Comment by mattip** [comment]
> delete the pre-7.3.9 patches

Done

**Comment by mattip** [comment]
Once this gets merged, I can rebuild the aarch64 and ppc packages on the gcc buildfarm. @isuruf once I do that how do I upload them?

**Comment by isuruf** [comment]
You can upload to your own channel and I can copy it. Can you keep the logs of building the package?
Btw, I can give you access to our machines. Otherwise you'll have to make sure to use docker or start with a clean CentOS 7 VM.

**Comment by mattip** [comment]
Access would be nice. I sent you a mail with my details

**Comment by mattip** [comment]
@isuruf I have uploaded the aarch64 and ppc64le packages to https://anaconda.org/mattip and attached the logs.txt files. 
[logs_aarch64.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/8456175/logs_aarch64.txt)
[logs_ppc64le.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/8456176/logs_ppc64le.txt)

The commands I used (slightly modified your recommendations) are at https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22

**Pull request merged**
