### PR TITLE
make object.j closer to CPython, fix scratch register issue in the JIT on windows

### LINKED ISSUE #84: Rebuild with windows JIT fix?
Not sure what the timeline for 7.3.10 is, the [milestone](https://foss.heptapod.net/pypy/pypy/-/milestones/11#tab-issues) still looks wide open. I was wondering if we should rebuild with the fix for https://foss.heptapod.net/pypy/pypy/-/issues/3753 to make some headway with scipy on pypy etc.

CC @mattip

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #84

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
Hmm. ssl is failing `test_wrong_cert_tls13` on macOSX with openssl1.1.1. I don't remember that from upstream. In the mean time upstream fixed a bug with the [hashes available in `hashlib`](https://foss.heptapod.net/pypy/pypy/-/issues/3741) but I think it is not connected.

**Comment by mattip** [comment]
Hmm. ssl is failing `test_wrong_cert_tls13` on macOSX with openssl1.1.1. I don't remember that from upstream, and a local build of the recipe on a m1 mini using rosetta passes. Is there a way to restart the failing builds?

**Comment by h-vetinari** [comment]
> Is there a way to restart the failing builds?

Seems that you (or someone else) did this already. If you click on "Details" for one of the azure jobs, there's a button on the left to restart the failed jobs. And you can always just comment `[at]conda-forge-admin, please restart ci` (replace [at]->@).

**Comment by mattip** [comment]
Cool, now CI is passing. Anyone want to review and/or merge?

**Review by h-vetinari — COMMENTED** [review]
> Cool, now CI is passing. Anyone want to review and/or merge?

Not that I'm officially a maintainer on this feedstock, but LGTM!

**Comment by mattip** [comment]
Merged, I wonder if it helps conda-forge/scipy-feedstock#204

**Comment by h-vetinari** [comment]
> Merged, I wonder if it helps [conda-forge/scipy-feedstock#204](https://github.com/conda-forge/scipy-feedstock/pull/204)

I really expect it to! :)

**Comment by mattip** [comment]
I forgot how to make aarch64 builds of PyPy. @isuruf it is something about building on a different machine, correct?

**Comment by h-vetinari** [comment]
If you check his [profile](https://github.com/isuruf), you'll see that Isuru's been gone completely for more than a month. He does have a [tweet](https://twitter.com/isuru_f) during that time though, so I think he's just focussing on something else right now. Might have to reach out through a different channel if you really need something from him.

**Comment by mattip** [comment]
I followed [the directions](https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22) from the last time and did the aarch64 builds. Here is the log
[logs.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/9236449/logs.txt)
The artifacts are the new files in these links. https://anaconda.org/mattip/pypy3.9/files and https://anaconda.org/mattip/pypy3.8/files

Could one of the conda-forge admins here upload them to https://anaconda.org/conda-forge/pypy3.9/files and https://anaconda.org/conda-forge/pypy3.8/files respectively?

**Pull request merged**
