### PR TITLE
Fix running pypy.exe without activating

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/pypy3.6-feedstock/issues/101
Fixes https://github.com/conda-forge/miniforge/issues/385

### CODE REVIEW

**Comment by isuruf** [comment]
@mattip, can you review?

**Comment by mattip** [comment]
Not until after sept 9, i am away from my windows machine. Is there a way to download the artifact to test?

**Comment by isuruf** [comment]
The artifacs can be found at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=774293&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by isuruf** [comment]
You can also do `mamba create -n pypy pypy -c isuruf/label/pypy`. I checked and it does work without activating the environment.

**Comment by mattip** [comment]
Let’s give it a shot

**Pull request merged**
