### PR TITLE
Versioning

### LINKED ISSUE #52: Fix platform._sys_version() for new sys.version stanza
In PR #51 we added " packaged by conda-forge " to the sys.version string which broke parsing in `platform._sys_version()`. As pointed out in [this comment](https://github.com/conda-forge/pypy3.6-feedstock/pull/51#discussion_r678827553) by @tkelman the regex needs changing.

On CPython the `sys.version` is 
```
3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
```
which is parsed into `(name, version, branch, revision, buildno, builddate, compiler)`  like
```
('CPython', '3.8.10', '', '', 'default', 'May 11 2021 06:25:23', 'MSC v.1916 64 bit (AMD64)')
```

On PyPy the sys.version is (two lines)
```
'3.7.10 | packaged by conda-forge | (77787b8f, Jul 28 2021, 14:32:04)
[PyPy 7.3.5 with MSC v.1916 64 bit (AMD64)]'
```
which used to be parsed (without the new stanza) into
```
('PyPy', '3.7.10', 'release-pypy3.7-v7.3.5rc3', '77787b8f', '77787b8f', 'Jul 18 2021', '')
```

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #52 by changing the regex for `platform._sys_version()`. Also fix parsing the hg tag so that `sys._mercurial` returns the lastest tag, not the earliest (this patch will be part of the next PyPy release)

Also add a test that `platform._sys_version()` does not crash

### CODE REVIEW

**Comment by mattip** [comment]
the new test [is printing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=357626&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=8236)
```
('PyPy', '3.7.10', 'release-pypy3.7-v7.3.5', '77787b8f', '77787b8f', 'Jul 29 2021', 'MSC v.1916 64 bit (AMD64)')
```

**Comment by mattip** [comment]
@isuruf should we try again to get this in?

**Comment by tkelman** [comment]
Do you think these should go upstream?

**Comment by mattip** [comment]
There are two patches here. The tag one (making sure the first tag is taken from the `.hg_archival.txt`) `patches/pre-7.3.6-0010.patch` has been upstreamed. The other one (adjusting platform._sys_version for conda-forge-specific `sys.version` string) is specific to conda-forge and should not be upstreamed to PyPy.

**Comment by tkelman** [comment]
You don't think the regex should be made to populate compiler, and have the revision be a consistent length with cpython, outside of conda-forge?

**Pull request merged**
