### PR TITLE
rebuild _sysconfigdata__*.py in $PREFIX so the install step will fix paths

### LINKED ISSUE #86: _sysconfigdata__*.py is not updated when the package is installed
The package to download has a `_sysconfigdata__*.py` file that captures the state at build time. This should be overwritten with information when the package is installed. For instance, the x86_64 downloaded package has 
`'INCLUDEPY': '/home/conda/feedstock_root/build_artifacts/pypy3.8_1658434607149/work/pypy3/include/pypy3.8'`
which is wrong once the package is installed. The CPython packages also have bogus paths, but these are somehow rewritten. The invocation to do this is 
`python -m sysconfig --generate-posix-vars`
Is that somehow run for CPython at installation but not for PyPy?

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #86. 
I tested this by seeing that the output of these commands shows the include files in the include directory
```
$ conda activate pypy3.8
$ conda install /home/matti/miniconda3/envs/python3.9/conda-bld/linux-64/pypy3.8-7.3.9-h5001382_3.tar.bz2
$ ls $(python -c "import sysconfig; print(sysconfig.get_config_var('INCLUDEPY'))")
```

### CODE REVIEW

**Comment by mattip** [comment]
If this looks right I will again build the aarch64 builds from [this gist](https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22)

**Comment by mattip** [comment]
MacOS builds are failing, I think this has to do with an update in the platform image. Upstream is using a patch to hardcode libc to `/usr/lib/lbic.dylib`. I will add a patch.

**Comment by mattip** [comment]
macOS cannot find libexpat, maybe adding it to the build environment will help

**Comment by mattip** [comment]
CI is passing. Would anyone like to take a look?

**Review by h-vetinari — COMMENTED** [review]
Looks alright, but just checking if the whitespace changes in the build scripts are really necessary (tab to space is fine, space to tab not so much)

**Comment by mattip** [comment]
@h-vetinari I meant to convert tabs to spaces. Did I mess up?

**Comment by h-vetinari** [comment]
I don't think so, but I couldn't tell which way the conversion went just by looking at the GH UI.

**Review by h-vetinari — APPROVED** [review]

**Comment by mattip** [comment]
I merged this. I will rebuild the aarch64 packages according to https://gist.github.com/mattip/1cb3c04fe1c285f62dfb4884cc1c5f22.

**Comment by mattip** [comment]
I built the result of this PR on an aarch64 machine, here are the build logs for the pypy3.8/pypy3.9 openblas1.1/openblas3 builds.

[logs.txt](https://github.com/conda-forge/pypy3.6-feedstock/files/9397975/logs.txt)


@conda-forge/pypy3-6 could someone copy the last 2 files from each of https://anaconda.org/mattip/pypy3.9/files and https://anaconda.org/mattip/pypy3.8/files (4 files total) to https://anaconda.org/conda-forge/pypy3.8/files and https://anaconda.org/conda-forge/pypy3.8/files respectively

**Comment by mattip** [comment]
@isuruf ping. Could you copy the aarch64 artifacts of the latest pypy3.8/pypy3.9 builds?

**Comment by isuruf** [comment]
Which artifacts exactly? Can you add a `copy` label to the artifacts to be copied?

**Comment by mattip** [comment]
> Can you add a copy label to the artifacts to be copied?

Done, thanks

**Comment by isuruf** [comment]
Copied just now

**Comment by mattip** [comment]
Thanks

**Pull request merged**
