### PR TITLE
Port TZPATH patch from CPython 3.9

### PR DESCRIPTION
**Pull request by xhochy**
Investigating whether we see https://github.com/conda-forge/backports.zoneinfo-feedstock/pull/16#issuecomment-1730791654 directly in CI here.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Awesome, we can at least replicate it.

**Comment by xhochy** [comment]
@conda-forge/pypy3-6 @isuruf  This is ready for review&merge.

**Comment by isuruf** [comment]
Thanks

**Comment by mattip** [comment]
I reopened the PyPy issue around this. Is is conda-specific or should PyPy be doing something different on windows? https://foss.heptapod.net/pypy/pypy/-/issues/3653

**Comment by mattip** [comment]
Ahh, I see CPython has a similar patch https://github.com/conda-forge/python-feedstock/blob/main/recipe/patches/0010-Fix-TZPATH-on-windows.patch

**Comment by xhochy** [comment]
The bug was introduced in PyPy once PyPy synced the respective module from CPython. Thus having the same patch on both sides is the most logical path.

**Pull request merged**
