### PR TITLE
update to 7.3.2

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
The patches no longer apply cleanly. I will try to fix this.

**Review by ohadravid — APPROVED** [review]
Maybe also add yourself to `recipe-maintainers:`? 😁

**Comment by mattip** [comment]
> Maybe also add yourself to recipe-maintainers?

How?

**Comment by ohadravid** [comment]
@mattip https://github.com/conda-forge/pypy3.6-feedstock/blob/master/recipe/meta.yaml#L77

**Comment by ohadravid** [comment]
@isuruf do you still need to manually create the ppc/arm versions?

**Comment by isuruf** [comment]
Yes, I've started the two builds.

**Comment by mattip** [comment]
I see the new package (7.3.2) via `conda search pypy3.6 --channel conda-forge`.
So I thought by now this would have percolated out enough so when I do `conda create -n pypy pypy` I would get the new version, but I still see `pypy3.6  conda-forge/linux-64::pypy3.6-7.3.1-h3e02ecb_1`. Is there something else that needs to be done to make 7.3.2 the default?

**Comment by isuruf** [comment]
Ah yes, we need to update https://github.com/conda-forge/pypy-meta-feedstock/blob/master/recipe/meta.yaml too

**Comment by mattip** [comment]
yay - conda create -n pypy pypy works! My next stupid question: in my current conda pypy3.6-v7.3.1 environment, how do I update pypy to 7.3.2? `conda update pypy` doesn't pull in a new version.

**Comment by mattip** [comment]
strangely, `conda update pypy3.6` *does* seem to pull in the new version, as does `conda install pypy=7.3.2`

**Pull request merged**
