### PR TITLE
Use conda-forge provided tzdata

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattip** [comment]
I can never remember the order of precedence between `sysconfig` and `_sysconfigdata`.
There is already a value in [`_sysconfigdata.py`](https://foss.heptapod.net/pypy/pypy/-/blob/branch/py3.9/lib_pypy/_sysconfigdata.py#L68). Will the one here override it? Perhaps it would be better to patch `_sysconfigdata.py` to avoid the question.

**Comment by isuruf** [comment]
Nvm, the unix values are fine. Needed to only fix the windows value.

Can you review again?

**Comment by isuruf** [comment]
We use the same patch for cpython at https://github.com/conda-forge/python-feedstock/blob/e1ea111b27632e9e9a6927d1b7dd25d4228549cc/recipe/patches/0016-Fix-TZPATH-on-windows.patch

**Comment by mattip** [comment]
> We use the same patch for cpython

+1

**Review by mattip — APPROVED** [review]
LGTM pending CI completion.

**Pull request merged**
